# Generated by Django 3.1.7 on 2021-03-15 09:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), size=None)),
                ('available', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Helper_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('skill', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
