# Generated by Django 3.1.7 on 2021-03-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helper_skill',
        ),
    ]
