# Generated by Django 3.1.7 on 2021-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_auto_20210315_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('skill', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
