# Generated by Django 3.1.7 on 2021-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_meetingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperdate',
            name='date',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
