# Generated by Django 3.1.7 on 2021-03-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0009_auto_20210323_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtable',
            name='meetinglink',
            field=models.CharField(default='', max_length=700),
        ),
    ]
