# Generated by Django 3.1.7 on 2021-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0010_auto_20210326_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
    ]
